apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mec-test-client
  namespace: default
  labels:
    app:  mec-test-client
spec:
  selector:
    matchLabels:
      app: mec-test-client
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mec-test-client
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name:  mec-test-client
        image:  ifilyaninitmo/mec-test-app-web:main
        ports:
        - containerPort:  3002
          name:  mec-test-client
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mec-test-client
  namespace: default
spec:
  selector:
    app: mec-test-client
  type: ClusterIP
  ports:
  - name: mec-test-client
    protocol: TCP
    port: 3010
    targetPort: 3002